Feature: Test With A Lot Of Data
    --------------------------------------------------------------------------------------------------------
    haha, sql goes brr
    Tagging: use @tag before each scenario, then run behave --tags="@wantedtag" --no-skipped
    #Complex tagging:
    #@a and @b
    #@a or  @b
    #not @a

    #@a and not @b
    #(@a or @b) and not @c
    --------------------------------------------------------------------------------------------------------
    
  Scenario Outline: Test Autogenerated Payload
    Given The numbers <number> and <multiplier>
    Then The answer is it doubled
      Examples:
        | number | multiplier |
        | 1      | 2          |
        | 2      | 2          |
        | 3      | 2          |
        | 4      | 2          |
        | 5      | 2          |
        | 6      | 2          |
        | 7      | 2          |

  @smoke
  Scenario Outline: A General Smoke Test
    Given The numbers <number> and <multiplier>
    Then The answer is it doubled
      Examples:
        | number | multiplier |
        | 1      | 2          |
