Feature: Test API
    --------------------------------------------------------------------------------------------------------
    First Cucumber feature file. Test is a general payload generation and posting it to https://httpbin.org/
    Oh my god this is just bureocracy. This does nothing but prettify code for non techies.
    Just one thing, dont put : between the keyword and string. That breaks it.
    --------------------------------------------------------------------------------------------------------
  
  @API
  Scenario: Test Autogenerated Payload
    Given The generated Payload through payload_generator()
    When The post request is issued
    Then A response with the payload is recieved